## selects_n_aggs

In [1]:
import pandas as pd

## Load the JSON file

In [2]:
df = pd.read_json("../data/auto.json")
df.set_index('CarNumber', inplace=True)

## Display the rows where the fines are greater than 2,100

In [3]:
df[df['Fines'] > 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
E40577152RUS       1   8594.586466        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[455 rows x 4 columns]

## Display the rows where the fines are greater than 2,100 and the refund equals 2

In [4]:
df[(df["Fines"] > 2100) & (df["Refund"] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[309 rows x 4 columns]

## Display the rows where the models are from the list: [’Focus’, ’Corolla’]

In [5]:
models = ['Focus', 'Corolla']
df.loc[df['Model'].isin(models)]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

## Display the rows where the car number is from the list:

In [6]:
cars_numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
df[df.index.isin(cars_numbers)]

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## Display the median fines grouped by make

In [7]:
df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

## Display the median fines grouped by make and model

In [8]:
df.groupby(['Make', 'Model'])['Fines'].median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

## Display the number of fines grouped by make and model

In [9]:
df.groupby(['Make', 'Model'])['Fines'].count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

## Display the minimum and maximum fines grouped by make and model

In [10]:
df.groupby(['Make', 'Model'])['Fines'].min()

Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64

In [11]:
df.groupby(['Make', 'Model'])['Fines'].max()

Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

## Display the standard deviation of fines grouped by make and model

In [12]:
df.groupby(['Make', 'Model'])['Fines'].std()

Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## Display the car numbers, grouped by the number of fines in descending order

In [13]:
cars_numbers_count = pd.DataFrame(df.groupby(df.index).count()['Fines'])
cars_numbers_count.sort_values('Fines', ascending=False, inplace=True)
cars_numbers_count

              Fines
CarNumber
Y7689C197RUS      4
7788KT197RUS      4
92928M178RUS      4
Y7129Y50RUS       3
X758HY197RUS      3
...             ...
Y967O8197RUS      1
Y965O8197RUS      1
Y965EE197RUS      1
Y964O8197RUS      1
Y964EE197RUS      1

[531 rows x 1 columns]

## Select from the initial dataframe all the rows corresponding to the top-1 car number

In [14]:
df[df.index == cars_numbers_count.index[0]]

              Refund    Fines  Make  Model
CarNumber
Y7689C197RUS       1  27000.0  Ford  Focus
Y7689C197RUS       2   9000.0  Ford  Focus
Y7689C197RUS       2  45000.0  Ford  Focus
Y7689C197RUS       1  36000.0  Ford  Focus

## Display the car numbers grouped by sum of fines in descending order

In [15]:
cars_numbers_sum = pd.DataFrame(df.groupby(df.index).sum()['Fines'])
cars_numbers_sum.sort_values('Fines', ascending=False, inplace=True)
cars_numbers_sum

                 Fines
CarNumber
X758HY197RUS  242000.0
9020YC197RUS  217500.0
M0279X197RUS  216000.0
Y352O8197RUS  207200.0
Y778EE197RUS  192000.0
...                ...
Y166O8161RUS     100.0
K326T8197RUS     100.0
Y195O8161RUS     100.0
C58078163RUS     100.0
705787163RUS     100.0

[531 rows x 1 columns]

## Select all the rows corresponding to the top-1 car number from the initial dataframe

In [16]:
df[df.index == cars_numbers_sum.index[0]]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

## Display a table that answers the question

In [17]:
pd.DataFrame(df.groupby(df.index)['Model'].nunique()).sort_values('Model', ascending=False)

              Model
CarNumber
Y973O8197RUS      1
704687163RUS      1
704787163RUS      1
Y7699C197RUS      1
Y7689C197RUS      1
...             ...
M5039X197RUS      0
H837YK197RUS      0
96907X197RUS      0
Y687HM197RUS      0
Y693HM197RUS      0

[531 rows x 1 columns]

## review

In [18]:
models = ['Focus', 'Corolla']
df.loc[df['Model'].isin(models)]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [19]:
df.groupby(['Make', 'Model']).agg('Fines').count()

Make        Model
Ford        Focus      575
            Mondeo       6
Skoda       Octavia     48
Toyota      Camry       16
            Corolla     18
Volkswagen  Golf        20
            Jetta        6
            Passat      22
            Touareg      5
Name: Fines, dtype: int64

In [20]:
cars_numbers_count

              Fines
CarNumber
Y7689C197RUS      4
7788KT197RUS      4
92928M178RUS      4
Y7129Y50RUS       3
X758HY197RUS      3
...             ...
Y967O8197RUS      1
Y965O8197RUS      1
Y965EE197RUS      1
Y964O8197RUS      1
Y964EE197RUS      1

[531 rows x 1 columns]

In [21]:
cars_numbers_sum

                 Fines
CarNumber
X758HY197RUS  242000.0
9020YC197RUS  217500.0
M0279X197RUS  216000.0
Y352O8197RUS  207200.0
Y778EE197RUS  192000.0
...                ...
Y166O8161RUS     100.0
K326T8197RUS     100.0
Y195O8161RUS     100.0
C58078163RUS     100.0
705787163RUS     100.0

[531 rows x 1 columns]