## basic_operations

In [24]:
import pandas as pd

## Dataframe views

In [25]:
views = pd.read_csv(filepath_or_buffer="../data/feed-views.log",
                 sep='\t',
                 header=None,
                 names=['datetime', 'user'],
                 engine='python')

In [26]:
views['datetime'] = views.datetime.astype('datetime64[ns]')

In [27]:
views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

## Create the new column daytime

In [28]:
views.set_index('user', inplace=True)
bins = [0, 4, 7, 11, 17, 20, 24]
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

views['daytime'] = pd.cut(views['hour'], bins=bins, labels=labels, right=False)

## Calculate the number of elements in dataframe

In [29]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [30]:
views.daytime.value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## Sort the values in dataframe

In [31]:
views_sorted = views.sort_values(by=['hour', 'minute', 'second'], inplace=True)

## Calculate the minimum and maximum

In [32]:
max_hour_night = views[views['daytime'] == 'night']['hour'].max()
views[views.hour == max_hour_night]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
konstantin,2020-04-19 03:23:35.471598,2020,4,19,3,23,35,night
konstantin,2020-04-19 03:23:55.473926,2020,4,19,3,23,55,night
konstantin,2020-04-19 03:33:07.757714,2020,4,19,3,33,7,night

In [33]:
min_hour_morning = views[views['daytime'] == 'morning']['hour'].min()
views[views.hour == min_hour_morning]

,datetime,year,month,day,hour,minute,second,daytime
user,,,,,,,,
alexander,2020-05-15 08:16:03.918402,2020,5,15,8,16,3,morning
alexander,2020-05-15 08:35:01.471463,2020,5,15,8,35,1,morning

In [34]:
views.hour.mode()

0    22
Name: hour, dtype: int32

In [35]:
views.daytime.mode()

0    evening
Name: daytime, dtype: category
Categories (6, str): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## The three earliest and latest hours of the day

In [36]:
views.nsmallest(3, 'hour')[['hour']]

           hour
user
valentina     0
valentina     0
pavel         0

In [37]:
views.nlargest(3, 'hour')[['hour']]

           hour
user
ekaterina    23
ekaterina    23
ekaterina    23

## Basic statistics

In [38]:
iqr = views.describe()['hour']['75%'] - views.describe()['hour']['25%']
iqr

np.float64(9.0)

## review

In [39]:
views.info()

<class 'pandas.DataFrame'>
Index: 1076 entries, valentina to alexander
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1076 non-null   datetime64[ns]
 1   year      1076 non-null   int32
 2   month     1076 non-null   int32
 3   day       1076 non-null   int32
 4   hour      1076 non-null   int32
 5   minute    1076 non-null   int32
 6   second    1076 non-null   int32
 7   daytime   1076 non-null   category
dtypes: category(1), datetime64[ns](1), int32(6)
memory usage: 75.6+ KB

In [40]:
views.count()

datetime    1076
year        1076
month       1076
day         1076
hour        1076
minute      1076
second      1076
daytime     1076
dtype: int64

In [41]:
views.daytime.value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

In [42]:
views.loc[views.daytime == 'night'].hour.idxmax()

'konstantin'

In [43]:
views.loc[views.daytime == 'morning'].hour.idxmin()

'alexander'

In [44]:
views.hour.mode()

0    22
Name: hour, dtype: int32

In [45]:
views.daytime.mode()

0    evening
Name: daytime, dtype: category
Categories (6, str): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

In [46]:
iqr

np.float64(9.0)