# 1. Answer the questions

## Derive an analytical solution to the regression problem. Use a vector form of the equation.

**1. Обозначения**

Пусть у нас есть $N$ наблюдений и $D$ признаков.

- y ∈ $\mathbb{R}^N$ — вектор целевых значений (размер $N×1$)
- $\theta∈\mathbb{R}^{D+1}$ — вектор параметров модели, включающий $b$ и все веса $w_1,\dots,w_D$
- $X$ — матрица признаков размера $N×(D+1)$. Первый столбец состоит из единиц и нужен для учёта свободного члена $b$

Вектор параметров $\theta$:

$$
\theta = \begin{pmatrix}
b \\
w_1 \\
w_2 \\
\dots \\
w_D
\end{pmatrix}
$$

Матрица признаков $X$:

$$
X = \begin{pmatrix}
1 & x_{11} & x_{12} & \dots & x_{1D} \\
1 & x_{21} & x_{22} & \dots & x_{2D} \\
\dots & \dots & \dots & \dots & \dots \\
1 & x_{N1} & x_{N2} & \dots & x_{ND}
\end{pmatrix}
$$

Модель:

$$
\hat{y} = X\theta = \begin{pmatrix}
b + w_1 x_{11} + w_2 x_{12} + \dots + w_D x_{1D} \\
b + w_1 x_{21} + w_2 x_{22} + \dots + w_D x_{2D} \\
\dots \\
b + w_1 x_{N1} + w_2 x_{N2} + \dots + w_D x_{ND}
\end{pmatrix}
$$

**2. Функция потерь**

Среднеквадратичная ошибка в векторной форме:

$$MSE(\theta) = \frac{1}{N}(y-X\theta)^T(y-X\theta)$$

Множитель $\frac{1}{N}$ не влияет на положение минимума, поэтому будем минимизировать сумму квадратов ошибок:

$$S(\theta) = (y-X\theta)^T(y-X\theta)$$

**3. Пошаговое дифференцирование**

Перед расчётом зафиксируем ключевые правила (для векторов и матриц):

- $\nabla_\theta (a^T \theta) = a$ — производная линейной формы;
- $\nabla_\theta (\theta^T A \theta) = (A + A^T)\theta$ — производная квадратичной формы;
- Если $A$ симметрична ($A = A^T$), то $\nabla_\theta (\theta^T A \theta) = 2A\theta$;
- $\nabla_\theta c = 0$, если $c$ не зависит от $\theta$.

Исходная функция:

$$S(\theta) = (y - X\theta)^T (y - X\theta)$$

**Шаг 1. Раскрытие скобок**

Раскроем выражение:

$$S(\theta) = y^T y - y^T X\theta - \theta^T X^T y + \theta^T X^T X\theta$$

Заметим, что $y^T X\theta$ и $\theta^T X^T y$ — скаляры и равны друг другу (поскольку транспонирование скаляра не меняет его значения):

$$y^T X\theta = \theta^T X^T y$$

Упрощаем:

$$S(\theta) = y^T y - 2\theta^T X^T y + \theta^T X^T X\theta$$

**Шаг 2. Дифференцирование каждого слагаемого**

**Первое слагаемое:** $y^T y$

- не зависит от $\theta$;
- по правилу 4: $\nabla_\theta (y^T y) = 0$.

**Второе слагаемое:** $-2\theta^T X^T y$

- это линейная форма относительно $\theta$;
- представим как $-2(\theta^T a)$, где $a = X^T y$;
- по правилу 1: $\nabla_\theta (\theta^T a) = a$;
- с учётом множителя $-2$: $\nabla_\theta (-2\theta^T X^T y) = -2X^T y$.

**Третье слагаемое:** $\theta^T X^T X\theta$

- это квадратичная форма $\theta^T A\theta$, где $A = X^T X$;
- матрица $A = X^T X$ всегда симметрична (поскольку $(X^T X)^T = X^T X$);
- применяем правило 3: $\nabla_\theta (\theta^T A\theta) = 2A\theta$;
- подставляем $A = X^T X$: $\nabla_\theta (\theta^T X^T X\theta) = 2X^T X\theta$.

**Шаг 3. Суммирование результатов**

Складываем градиенты всех слагаемых:

$$\nabla_\theta S(\theta) = \nabla_\theta (y^T y) + \nabla_\theta (-2\theta^T X^T y) + \nabla_\theta (\theta^T X^T X\theta)$$

Подставляем найденные значения:

$$\nabla_\theta S(\theta) = 0 - 2X^T y + 2X^T X\theta$$

Выносим общий множитель $-2X^T$:

$$\nabla_\theta S(\theta) = -2X^T (y - X\theta)$$

**Шаг 4. Поиск минимума**

Раскроем скобки:

$$X^Ty-X^TX\theta = 0$$

Получаем систему нормальных уравнений:

$$X^TX\theta = X^Ty$$

**4. Аналитическое решение**

Если матрица $X^TX$ обратима, решение имеет вид:

$$\boxed{\theta=(X^TX)^{-1}X^Ty}$$

Это и есть аналитическое решение задачи линейной регрессии методом наименьших квадратов.

**5. Примечание**

- Решение существует и единственно, если столбцы матрицы $X$ линейно независимы (нет строгой мультиколлинеарности)
- При нарушении условия обратимости применяют регуляризацию (Lasso, Ridge) или псевдообратную матрицу

## What changes in the solution when L1 and L2 regularizations are added to the loss function.

В общем виде регуляризованная функция потерь содержит дополнительный штрафной член $R(\theta)$:
$$\min_\theta \sum_{i=1}^N L\bigl(f(x_i,\theta), y_i\bigr) + \lambda R(\theta)$$

**L2-регуляризация (Ridge):** $R(\theta) = \|\theta\|_2^2 = \sum_{i=1}^d \theta_i^2$

Аналитическое решение принимает вид:
$$\theta = (X^T X + \lambda I)^{-1} X^T y$$
Матрица $X^T X + \lambda I$ всегда обратима (даже при мультиколлинеарности). Веса сжимаются к нулю, но **не обнуляются**.

**L1-регуляризация (Lasso):** $R(\theta) = \|\theta\|_1 = \sum_{i=1}^d |\theta_i|$

Аналитического решения нет. Из-за модуля в штрафе многие коэффициенты становятся **точно равными нулю** (разреженность). Оптимум ищут итеративно (субградиентные методы, coordinate descent).

## Explain why L1 regularization is often used to select features. Why are there many weights equal to 0 after the model is fit?

L1-регуляризация добавляет штраф $R(\theta) = \|\theta\|_1 = \sum_{i=1}^d |\theta_i|$.
Каждый ненулевой коэффициент увеличивает штраф. Если вклад некоторого признака в уменьшение ошибки мал (меньше $\lambda$), оптимальным становится $\theta_j = 0$.
Таким образом, L1 автоматически приводит к разреженным решениям и может использоваться для **отбора признаков**: неинформативные признаки получают нулевые веса.

## Explain how you can use the same models (Linear regression, Ridge, etc.) but make it possible to fit nonlinear dependencies.

Модель остаётся **линейной по параметрам**, но признаки предварительно преобразуются нелинейно.
Вместо $X$ используется матрица $\Phi = \phi(X)$, где $\phi$ – нелинейное отображение.

**Примеры преобразований**

$$\phi(x) = (x, x^2, x^3, \dots, x^d)$$

или

$$\phi(x_1,x_2) = (x_1, x_2, x_1x_2, x_1^2, x_2^2, \dots)$$

**Модель с преобразованными признаками**

$$\hat{y} = \Phi\theta$$

Все методы (аналитическое решение OLS, SGD, Ridge, Lasso) применяются к $\Phi$ без изменений. Регуляризация особенно важна, так как большое число полиномиальных признаков легко ведёт к переобучению.

# 2. Introduction

## Import libraries.

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import MinMaxScaler
import lightgbm
import scipy
import statsmodels
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

## Read Train and Test Parts.

In [2]:
train_df = pd.read_json('../datasets/train.json')
test_df = pd.read_json('../datasets/test.json')

# 3. Intro data analysis part 2

## Let's generate additional features for better model quality. Consider a column called "Features". It consists of a list of highlights of the current flat.

In [3]:
print(train_df['features'].iloc[0])

['Dining Room', 'Pre-War', 'Laundry in Building', 'Dishwasher', 'Hardwood Floors', 'Dogs Allowed', 'Cats Allowed']

## Remove unused symbols ([,], ', ", and space) from the column.

Так как колонка `features` уже загружена из JSON как списки строк, символы `[`, `]`, `'` и `"` в данных отсутствуют. Очистка не требуется.

## Get all values in each list and collect the result in one huge list for the whole dataset. You can use DataFrame.iterrows().

In [4]:
all_features = []
for idx, row in train_df.iterrows():
    features_list = row['features']
    if not features_list:
        continue
    for item in features_list:
        clean_item = item.replace(" ", "")
        all_features.append(clean_item)

## How many unique values does a result list contain?

In [5]:
unique_count = len(set(all_features))
print(f"Уникальных значений: {unique_count}")

Уникальных значений: 1548

## Let's get acquainted with the new library — Collections. With this package you could effectively get quantity statistics about your data.

In [6]:
feature_counter = Counter(all_features)
feature_counter.most_common(21)

[('Elevator', 25915),
 ('CatsAllowed', 23540),
 ('HardwoodFloors', 23527),
 ('DogsAllowed', 22035),
 ('Doorman', 20898),
 ('Dishwasher', 20426),
 ('NoFee', 18062),
 ('LaundryinBuilding', 16344),
 ('FitnessCenter', 13252),
 ('Pre-War', 9148),
 ('LaundryinUnit', 8738),
 ('RoofDeck', 6542),
 ('OutdoorSpace', 5268),
 ('DiningRoom', 5136),
 ('HighSpeedInternet', 4299),
 ('Balcony', 2992),
 ('SwimmingPool', 2730),
 ('LaundryInBuilding', 2593),
 ('NewConstruction', 2559),
 ('Terrace', 2283),
 ('Exclusive', 2167)]

## Count the most popular functions from our huge list and take the top 20 for this moment.

In [7]:
top20 = [item for item, count in feature_counter.most_common(20)]
print(*top20, sep="\n")

Elevator
CatsAllowed
HardwoodFloors
DogsAllowed
Doorman
Dishwasher
NoFee
LaundryinBuilding
FitnessCenter
Pre-War
LaundryinUnit
RoofDeck
OutdoorSpace
DiningRoom
HighSpeedInternet
Balcony
SwimmingPool
LaundryInBuilding
NewConstruction
Terrace

## If everything is correct, you should get next values: 'Elevator', 'CatsAllowed', 'HardwoodFloors', 'DogsAllowed', 'Doorman', 'Dishwasher', 'NoFee', 'LaundryinBuilding', 'FitnessCenter', 'Pre-War', 'LaundryinUnit', 'RoofDeck', 'OutdoorSpace', 'DiningRoom', 'HighSpeedInternet', 'Balcony', 'SwimmingPool', 'LaundryInBuilding', 'NewConstruction', 'Terrace'.

## Now create 20 new features based on the top 20 values: 1 if the value is in the "Feature" column, otherwise 0.

In [8]:
for feature in top20:
    train_df[feature] = train_df['features'].apply(
        lambda lst: 1 if feature in [f.replace(" ", "") for f in lst] else 0
    )
    test_df[feature] = test_df['features'].apply(
        lambda lst: 1 if feature in [f.replace(" ", "") for f in lst] else 0
    )

## Extend our feature set with 'bathrooms', 'bedrooms' and create a special variable feature_list with all feature names. Now we have 22 values. All models should be trained on these 22 features.

In [9]:
feature_list = top20 + ['bathrooms', 'bedrooms']
print(f"Всего признаков: {len(feature_list)}")
print(*feature_list, sep="\n")

Всего признаков: 22
Elevator
CatsAllowed
HardwoodFloors
DogsAllowed
Doorman
Dishwasher
NoFee
LaundryinBuilding
FitnessCenter
Pre-War
LaundryinUnit
RoofDeck
OutdoorSpace
DiningRoom
HighSpeedInternet
Balcony
SwimmingPool
LaundryInBuilding
NewConstruction
Terrace
bathrooms
bedrooms

# 4. Models implementation — Linear regression

## Implement a Python class for a linear regression algorithm with two basic methods — fit and predict. Use stochastic gradient descent (SGD) to find optimal model weights. For better understanding, we recommend implementing separate versions of the algorithm with the analytical solution and non-stochastic gradient descent under the hood.

In [10]:
class MyLinearRegression:
    def __init__(self, learning_rate=0.01, epochs=100, random_state=42):
        self.lr = learning_rate
        self.epochs = epochs
        self.random_state = random_state
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        X_vals = X.values if hasattr(X, 'values') else X
        y_vals = y.values if hasattr(y, 'values') else y

        for _ in range(self.epochs):
            for i in range(n_samples):
                idx = np.random.randint(0, n_samples)
                x_i = X_vals[idx]
                y_i = y_vals[idx]

                y_pred = np.dot(x_i, self.weights) + self.bias
                error = y_pred - y_i

                self.weights -= self.lr * (2 * x_i * error)
                self.bias -= self.lr * (2 * error)

    def predict(self, X):
        X_vals = X.values if hasattr(X, 'values') else X
        return np.dot(X_vals, self.weights) + self.bias

## What is determenistic model? Make SGD determenistic.

Детерминированная модель — модель, которая при одних и тех же входных данных и начальных условиях всегда выдаёт одинаковый результат.
Для детерминированности SGD мы фиксируем `random_state` и устанавливаем `np.random.seed(self.random_state)` в начале `fit`.

## Define the R squared (R2) coefficient and implement a function to calculate it.

In [11]:
def r2_score_custom(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ss_res / ss_tot)

## Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.

In [ ]:
# Удаляем выбросы
Q1 = train_df['price'].quantile(0.2)
Q3 = train_df['price'].quantile(0.8)
IQR = Q3 - Q1
train_df = train_df[(train_df['price'] >= (Q1 - 1.5 * IQR)) & (train_df['price'] <= (Q3 + 1.5 * IQR))]

X = train_df[feature_list]
y = train_df['price']

# Разделение на train/test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Масштабирование (важно для SGD)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

my_model = MyLinearRegression(learning_rate=0.001, epochs=100, random_state=42)
my_model.fit(X_train_scaled, y_train)

my_train_pred = my_model.predict(X_train_scaled)
my_test_pred = my_model.predict(X_test_scaled)

print("My Linear Regression (SGD):")
print("Train MAE:", mean_absolute_error(y_train, my_train_pred))
print("Test MAE:", mean_absolute_error(y_test, my_test_pred))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, my_train_pred)))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, my_test_pred)))
print("Train R2:", r2_score_custom(y_train, my_train_pred))
print("Test R2:", r2_score_custom(y_test, my_test_pred))

## Initialize LinearRegression() from sklearn.linear_model, fit the model, and predict the training and test parts as in the previous lesson.

In [13]:
sk_model = LinearRegression()
sk_model.fit(X_train_scaled, y_train)

sk_train_pred = sk_model.predict(X_train_scaled)
sk_test_pred = sk_model.predict(X_test_scaled)

print("Sklearn Linear Regression:")
print("Train MAE:", mean_absolute_error(y_train, sk_train_pred))
print("Test MAE:", mean_absolute_error(y_test, sk_test_pred))
print("Train RMSE:", np.sqrt(mean_squared_error(y_train, sk_train_pred)))
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, sk_test_pred)))
print("Train R2:", r2_score_custom(y_train, sk_train_pred))
print("Test R2:", r2_score_custom(y_test, sk_test_pred))

Sklearn Linear Regression:
Train MAE: 626.9844659420562
Test MAE: 638.0197301696878
Train RMSE: 840.1918844769094
Test RMSE: 854.1148422687448
Train R2: 0.5449764682856441
Test R2: 0.5387152184010053

## Compare the quality metrics and make sure the difference is small (between your implementations and sklearn).

## Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

In [14]:
result_MAE = pd.DataFrame(columns=['model', 'train', 'test'])
result_RMSE = pd.DataFrame(columns=['model', 'train', 'test'])
result_R2 = pd.DataFrame(columns=['model', 'train', 'test'])

def add_to_tables(name, train_true, train_pred, test_true, test_pred):
    global result_MAE, result_RMSE, result_R2
    # MAE
    result_MAE = pd.concat([result_MAE, pd.DataFrame({
        'model': [name],
        'train': [mean_absolute_error(train_true, train_pred)],
        'test': [mean_absolute_error(test_true, test_pred)]
    })], ignore_index=True)
    # RMSE
    result_RMSE = pd.concat([result_RMSE, pd.DataFrame({
        'model': [name],
        'train': [np.sqrt(mean_squared_error(train_true, train_pred))],
        'test': [np.sqrt(mean_squared_error(test_true, test_pred))]
    })], ignore_index=True)
    # R2
    result_R2 = pd.concat([result_R2, pd.DataFrame({
        'model': [name],
        'train': [r2_score_custom(train_true, train_pred)],
        'test': [r2_score_custom(test_true, test_pred)]
    })], ignore_index=True)

add_to_tables('my_sgd_lr', y_train, my_train_pred, y_test, my_test_pred)
add_to_tables('sklearn_lr', y_train, sk_train_pred, y_test, sk_test_pred)

print("MAE Table:")
print(result_MAE)
print("\nRMSE Table:")
print(result_RMSE)
print("\nR2 Table:")
print(result_R2)

MAE Table:
        model       train        test
0   my_sgd_lr  633.008591  644.797241
1  sklearn_lr  626.984466   638.01973

RMSE Table:
        model       train        test
0   my_sgd_lr  844.075622  858.878885
1  sklearn_lr  840.191884  854.114842

R2 Table:
        model     train      test
0   my_sgd_lr   0.54076  0.533555
1  sklearn_lr  0.544976  0.538715

# 5. Regularized models implementation — Ridge, Lasso, ElasticNet

## Implement Ridge, Lasso, ElasticNet algorithms: extend the loss function with L2, L1 and both regularizations accordingly.

In [15]:
class MyRegularizedRegression:
    def __init__(self, lr=0.001, epochs=100, alpha=0.1, l1_ratio=0.5, reg_type='ridge', random_state=42):
        self.lr = lr
        self.epochs = epochs
        self.alpha = alpha        # сила регуляризации
        self.l1_ratio = l1_ratio  # только для elastic
        self.reg_type = reg_type  # 'ridge', 'lasso', 'elastic'
        self.random_state = random_state
        self.weights = None
        self.bias = None

    def fit(self, X, y):
        np.random.seed(self.random_state)
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        X_vals = X.values if hasattr(X, 'values') else X
        y_vals = y.values if hasattr(y, 'values') else y

        for _ in range(self.epochs):
            for i in range(n_samples):
                idx = np.random.randint(0, n_samples)
                x_i = X_vals[idx]
                y_i = y_vals[idx]

                y_pred = np.dot(x_i, self.weights) + self.bias
                error = y_pred - y_i

                # Градиент ошибки без регуляризации
                grad_w = 2 * x_i * error
                grad_b = 2 * error

                # Добавляем штраф
                if self.reg_type == 'ridge':
                    grad_w += 2 * self.alpha * self.weights
                elif self.reg_type == 'lasso':
                    grad_w += self.alpha * np.sign(self.weights)
                elif self.reg_type == 'elastic':
                    grad_w += (self.alpha * self.l1_ratio * np.sign(self.weights) +
                               2 * self.alpha * (1 - self.l1_ratio) * self.weights)

                self.weights -= self.lr * grad_w
                self.bias -= self.lr * grad_b

    def predict(self, X):
        X_vals = X.values if hasattr(X, 'values') else X
        return np.dot(X_vals, self.weights) + self.bias

## Make predictions with your algorithm and estimate the model with MAE, RMSE and R2 metrics.

In [ ]:
my_ridge = MyRegularizedRegression(reg_type='ridge', alpha=0.1)
my_lasso = MyRegularizedRegression(reg_type='lasso', alpha=0.1)
my_elastic = MyRegularizedRegression(reg_type='elastic', alpha=0.1, l1_ratio=0.5)

my_ridge.fit(X_train_scaled, y_train)
my_lasso.fit(X_train_scaled, y_train)
my_elastic.fit(X_train_scaled, y_train)

for name, model in [('my_ridge', my_ridge), ('my_lasso', my_lasso), ('my_elastic', my_elastic)]:
    tr_pred = model.predict(X_train_scaled)
    te_pred = model.predict(X_test_scaled)
    print(f"{name}:")
    print(f"  Train MAE: {mean_absolute_error(y_train, tr_pred):.2f}")
    print(f"  Test MAE:  {mean_absolute_error(y_test, te_pred):.2f}")
    print(f"  Train R2:  {r2_score_custom(y_train, tr_pred):.4f}")
    print(f"  Test R2:   {r2_score_custom(y_test, te_pred):.4f}\n")
    add_to_tables(name, y_train, tr_pred, y_test, te_pred)

## Initialize Ridge(), Lasso(), and ElasticNet() from sklearn.linear_model, fit the model, and make predictions for the training and test samples as in the previous lesson.

In [17]:
sk_ridge = Ridge(alpha=0.1)
sk_lasso = Lasso(alpha=0.1)
sk_elastic = ElasticNet(alpha=0.1, l1_ratio=0.5)

sk_ridge.fit(X_train_scaled, y_train)
sk_lasso.fit(X_train_scaled, y_train)
sk_elastic.fit(X_train_scaled, y_train)

for name, model in [('sk_ridge', sk_ridge), ('sk_lasso', sk_lasso), ('sk_elastic', sk_elastic)]:
    tr_pred = model.predict(X_train_scaled)
    te_pred = model.predict(X_test_scaled)
    print(f"{name}:")
    print(f"  Train MAE: {mean_absolute_error(y_train, tr_pred):.2f}")
    print(f"  Test MAE:  {mean_absolute_error(y_test, te_pred):.2f}")
    print(f"  Train R2:  {r2_score_custom(y_train, tr_pred):.4f}")
    print(f"  Test R2:   {r2_score_custom(y_test, te_pred):.4f}\n")
    add_to_tables(name, y_train, tr_pred, y_test, te_pred)

sk_ridge:
  Train MAE: 626.98
  Test MAE:  638.02
  Train R2:  0.5450
  Test R2:   0.5387

sk_lasso:
  Train MAE: 626.99
  Test MAE:  638.03
  Train R2:  0.5450
  Test R2:   0.5387

sk_elastic:
  Train MAE: 628.22
  Test MAE:  639.68
  Train R2:  0.5442
  Test R2:   0.5377

## Compare quality metrics and make sure the difference is small (between your implementations and sklearn).

In [18]:
print("\nMAE:")
print(result_MAE)
print("\nRMSE:")
print(result_RMSE)
print("\nR2:")
print(result_R2)

for name in ['my_ridge', 'my_lasso', 'my_elastic']:
    sk_name = 'sk_' + name.split('_')[1]  # sk_ridge, sk_lasso, sk_elastic
    sk_row = result_R2[result_R2['model'] == sk_name]
    my_row = result_R2[result_R2['model'] == name]
    if not sk_row.empty and not my_row.empty:
        diff_train = abs(sk_row['train'].values[0] - my_row['train'].values[0])
        diff_test = abs(sk_row['test'].values[0] - my_row['test'].values[0])
        print(f"{name} vs {sk_name}: разница R2 train={diff_train:.4f}, test={diff_test:.4f}")

MAE:
        model       train        test
0   my_sgd_lr  633.008591  644.797241
1  sklearn_lr  626.984466   638.01973
2    my_ridge  638.799933  650.837118
3    my_lasso  633.013291  644.803621
4  my_elastic  635.419009  647.353136
5    sk_ridge  626.984495  638.019789
6    sk_lasso  626.985752  638.034052
7  sk_elastic  628.224366   639.68324

RMSE:
        model       train        test
0   my_sgd_lr  844.075622  858.878885
1  sklearn_lr  840.191884  854.114842
2    my_ridge  847.863238  862.737391
3    my_lasso  844.078919  858.884717
4  my_elastic  845.400389  860.262492
5    sk_ridge  840.191884  854.114857
6    sk_lasso  840.192234  854.127145
7  sk_elastic  840.949391  855.087456

R2:
        model     train      test
0   my_sgd_lr   0.54076  0.533555
1  sklearn_lr  0.544976  0.538715
2    my_ridge  0.536629  0.529355
3    my_lasso  0.540757  0.533549
4  my_elastic  0.539317  0.532051
5    sk_ridge  0.544976  0.538715
6    sk_lasso  0.544976  0.538702
7  sk_elastic  0.544156  0.537664
my_ridge vs sk_ridge: разница R2 train=0.0083, test=0.0094
my_lasso vs sk_lasso: разница R2 train=0.0042, test=0.0052
my_elastic vs sk_elastic: разница R2 train=0.0048, test=0.0056

## Store the metrics as in the previous lesson in a table with columns model, train, test for MAE table, RMSE table, and R2 coefficient.

In [19]:
display(result_MAE)
display(result_RMSE)
display(result_R2)

        model       train        test
0   my_sgd_lr  633.008591  644.797241
1  sklearn_lr  626.984466   638.01973
2    my_ridge  638.799933  650.837118
3    my_lasso  633.013291  644.803621
4  my_elastic  635.419009  647.353136
5    sk_ridge  626.984495  638.019789
6    sk_lasso  626.985752  638.034052
7  sk_elastic  628.224366   639.68324

        model       train        test
0   my_sgd_lr  844.075622  858.878885
1  sklearn_lr  840.191884  854.114842
2    my_ridge  847.863238  862.737391
3    my_lasso  844.078919  858.884717
4  my_elastic  845.400389  860.262492
5    sk_ridge  840.191884  854.114857
6    sk_lasso  840.192234  854.127145
7  sk_elastic  840.949391  855.087456

        model     train      test
0   my_sgd_lr   0.54076  0.533555
1  sklearn_lr  0.544976  0.538715
2    my_ridge  0.536629  0.529355
3    my_lasso  0.540757  0.533549
4  my_elastic  0.539317  0.532051
5    sk_ridge  0.544976  0.538715
6    sk_lasso  0.544976  0.538702
7  sk_elastic  0.544156  0.537664

# 6. Feature normalization

## First, write several examples of why and where feature normalization is mandatory and vice versa.

**Когда нормализация обязательна:**
- Линейные модели с градиентным спуском (Linear Regression, Logistic Regression, Neural Networks) – без масштабирования сходимость медленная или отсутствует.
- Алгоритмы, основанные на расстоянии (KNN, SVM, K-Means) – доминирование признака с большим масштабом.
- Регуляризованные модели (Ridge, Lasso) – штраф зависит от масштаба коэффициентов.

**Когда нормализация не обязательна:**
- Деревья решений и ансамбли (Random Forest, XGBoost, LightGBM) – они работают с порогами, масштаб не важен.
- Наивный байесовский классификатор (если признаки уже интерпретируемы).

## Let's consider the first of the classical normalization methods — MinMaxScaler. Write a mathematical formula for this method.

Формула MinMaxScaler:
$$
X_{\text{norm}} = \frac{X - X_{\min}}{X_{\max} - X_{\min}}
$$

## Implement your own function or class for MinMaxScaler feature normalization.

In [20]:
class MyMinMaxScaler:
    def __init__(self):
        self.min = None
        self.max = None

    def fit(self, X):
        self.min = np.min(X, axis=0)
        self.max = np.max(X, axis=0)

    def transform(self, X):
        return (X - self.min) / (self.max - self.min)

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

## Initialize MinMaxScaler() from sklearn.preprocessing.

In [21]:
from sklearn.preprocessing import MinMaxScaler

data_sample = X_train[['bathrooms', 'bedrooms']].values[:5]

my_scaler = MyMinMaxScaler()
my_scaled = my_scaler.fit_transform(data_sample)

sk_scaler = MinMaxScaler()
sk_scaled = sk_scaler.fit_transform(data_sample)

print("Разница между MyMinMaxScaler и sklearn MinMaxScaler:", np.sum(np.abs(my_scaled - sk_scaled)))

Разница между MyMinMaxScaler и sklearn MinMaxScaler: 0.0

## Compare the feature normalization with your own method and with sklearn.

## Repeat the steps from b to e for another normalization method StandardScaler.

In [22]:
class MyStandardScaler:
    def __init__(self):
        self.mean = None
        self.std = None

    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)

    def transform(self, X):
        return (X - self.mean) / self.std

    def fit_transform(self, X):
        self.fit(X)
        return self.transform(X)

my_std_scaler = MyStandardScaler()
my_std_scaled = my_std_scaler.fit_transform(data_sample)

sk_std_scaler = StandardScaler()
sk_std_scaled = sk_std_scaler.fit_transform(data_sample)

print("Разница между MyStandardScaler и sklearn StandardScaler:", np.sum(np.abs(my_std_scaled - sk_std_scaled)))

Разница между MyStandardScaler и sklearn StandardScaler: 0.0

# 7. Fit custom and sklearn models with normalized data

## Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with MinMaxScaler.

In [23]:
models = {
    'Linear': LinearRegression(),
    'Ridge': Ridge(alpha=1.0),
    'Lasso': Lasso(alpha=1.0),
    'ElasticNet': ElasticNet(alpha=1.0, l1_ratio=0.5)
}

minmax_scaler = MinMaxScaler()
X_train_minmax = minmax_scaler.fit_transform(X_train)
X_test_minmax = minmax_scaler.transform(X_test)

for model_name, model in models.items():
    model.fit(X_train_minmax, y_train)
    train_pred = model.predict(X_train_minmax)
    test_pred = model.predict(X_test_minmax)
    full_name = f"{model_name}_MinMax"
    add_to_tables(full_name, y_train, train_pred, y_test, test_pred)

print("Модели с MinMaxScaler обучены и добавлены в таблицы")

Модели с MinMaxScaler обучены и добавлены в таблицы

## Fit all models — Linear Regression, Ridge, Lasso, and ElasticNet — with StandardScaler.

In [24]:
std_scaler = StandardScaler()
X_train_std = std_scaler.fit_transform(X_train)
X_test_std = std_scaler.transform(X_test)

for model_name, model in models.items():
    model.fit(X_train_std, y_train)
    train_pred = model.predict(X_train_std)
    test_pred = model.predict(X_test_std)
    full_name = f"{model_name}_Standard"
    add_to_tables(full_name, y_train, train_pred, y_test, test_pred)

print("Модели с StandardScaler обучены и добавлены в таблицы")

Модели с StandardScaler обучены и добавлены в таблицы

## Add all results to our dataframe with metrics on samples.

In [25]:
print("Текущие метрики (MAE):")
display(result_MAE)
print("\nТекущие метрики (RMSE):")
display(result_RMSE)
print("\nТекущие метрики (R2):")
display(result_R2)

Текущие метрики (MAE):

                  model       train        test
0             my_sgd_lr  633.008591  644.797241
1            sklearn_lr  626.984466   638.01973
2              my_ridge  638.799933  650.837118
3              my_lasso  633.013291  644.803621
4            my_elastic  635.419009  647.353136
5              sk_ridge  626.984495  638.019789
6              sk_lasso  626.985752  638.034052
7            sk_elastic  628.224366   639.68324
8         Linear_MinMax  626.984466   638.01973
9          Ridge_MinMax  627.287112  638.246716
10         Lasso_MinMax  628.291324  639.428595
11    ElasticNet_MinMax  901.185925  915.472799
12      Linear_Standard  626.984466   638.01973
13       Ridge_Standard  626.984758  638.020321
14       Lasso_Standard  627.023795  638.173474
15  ElasticNet_Standard  662.528996  675.369835

Текущие метрики (RMSE):

                  model        train         test
0             my_sgd_lr   844.075622   858.878885
1            sklearn_lr   840.191884   854.114842
2              my_ridge   847.863238   862.737391
3              my_lasso   844.078919   858.884717
4            my_elastic   845.400389   860.262492
5              sk_ridge   840.191884   854.114857
6              sk_lasso   840.192234   854.127145
7            sk_elastic   840.949391   855.087456
8         Linear_MinMax   840.191884   854.114842
9          Ridge_MinMax   840.225533   854.041749
10         Lasso_MinMax   840.750782    854.55044
11    ElasticNet_MinMax  1159.240348  1172.105542
12      Linear_Standard   840.191884   854.114842
13       Ridge_Standard   840.191885   854.114992
14       Lasso_Standard   840.223377   854.258959
15  ElasticNet_Standard   874.213291   888.663844

Текущие метрики (R2):

                  model     train      test
0             my_sgd_lr   0.54076  0.533555
1            sklearn_lr  0.544976  0.538715
2              my_ridge  0.536629  0.529355
3              my_lasso  0.540757  0.533549
4            my_elastic  0.539317  0.532051
5              sk_ridge  0.544976  0.538715
6              sk_lasso  0.544976  0.538702
7            sk_elastic  0.544156  0.537664
8         Linear_MinMax  0.544976  0.538715
9          Ridge_MinMax   0.54494  0.538794
10         Lasso_MinMax  0.544371  0.538245
11    ElasticNet_MinMax  0.133789    0.1313
12      Linear_Standard  0.544976  0.538715
13       Ridge_Standard  0.544976  0.538715
14       Lasso_Standard  0.544942   0.53856
15  ElasticNet_Standard   0.50738  0.500642

# 8. Overfit models

## Let's look at an overfitted model in practice. From theory, you know that polynomial regression is easy to overfit. So let's create a toy example and see how regularization works in real life.

In [26]:
X_poly_base = train_df[['bathrooms', 'bedrooms']]
y_poly = train_df['price']
X_poly_base = train_df[['bathrooms', 'bedrooms']]
y_poly = train_df['price']

X_tr_poly, X_te_poly, y_tr_poly, y_te_poly = train_test_split(X_poly_base, y_poly, test_size=0.2, random_state=42)

poly = PolynomialFeatures(degree=10)
X_train_poly = poly.fit_transform(X_tr_poly)
X_test_poly = poly.transform(X_te_poly)

scaler_poly = StandardScaler()
X_train_poly_scaled = scaler_poly.fit_transform(X_train_poly)
X_test_poly_scaled = scaler_poly.transform(X_test_poly)

print(f"Количество полиномиальных признаков: {X_train_poly_scaled.shape[1]}")

Количество полиномиальных признаков: 66

## In the previous lesson, we created polynomial features with degree 10. Here we repeat these steps from the previous lesson, remembering that we have only 2 basic features — 'bathrooms' and 'bedrooms'.

## And train and fit all our implemented algorithms — Linear Regression, Ridge, Lasso, and ElasticNet — on a set of polynomial features.

In [27]:
poly_models = {
    'LR_poly10': LinearRegression(),
    'Ridge_poly10': Ridge(alpha=10.0),
    'Lasso_poly10': Lasso(alpha=10.0),
    'Elastic_poly10': ElasticNet(alpha=1.0, l1_ratio=0.5)
}

for name, model in poly_models.items():
    model.fit(X_train_poly_scaled, y_tr_poly)
    tr_pred = model.predict(X_train_poly_scaled)
    te_pred = model.predict(X_test_poly_scaled)
    add_to_tables(name, y_tr_poly, tr_pred, y_te_poly, te_pred)

print("Метрики полиномиальных моделей добавлены")

Метрики полиномиальных моделей добавлены

## Store the results of the quality metrics in the result dataframe.

In [28]:
print("Результаты полиномиальных моделей:")
display(result_MAE.tail(4))
display(result_RMSE.tail(4))
display(result_R2.tail(4))

Результаты полиномиальных моделей:

             model       train        test
16       LR_poly10  685.518993  766.647085
17    Ridge_poly10  687.931986  699.305664
18    Lasso_poly10  698.585245  712.051356
19  Elastic_poly10   711.81973  724.579994

             model       train         test
16       LR_poly10   906.66754  5750.002855
17    Ridge_poly10  911.192315   925.875427
18    Lasso_poly10  923.854861    942.65723
19  Elastic_poly10  939.064094   954.108964

             model     train       test
16       LR_poly10  0.470125 -19.906085
17    Ridge_poly10  0.464824   0.457947
18    Lasso_poly10  0.449846   0.438119
19  Elastic_poly10  0.431583   0.424384

## Analyze the results and select the best model according to your opinion.

Среди полиномиальных моделей видно, что обычная линейная регрессия (LR_poly10) катастрофически переобучается (R² на тесте отрицательный и огромный по модулю). Ridge, Lasso и ElasticNet значительно лучше за счет регуляризации. Лучший баланс между качеством на трейне и тесте показывает Ridge_poly10 (R² ~ 0.42 на тесте).

## Additionally try different alpha parameters of regularization in algorithms, choose the best one and analyze results.

In [29]:
alphas = [0.001, 0.1, 1, 10, 100, 1000]
for a in alphas:
    ridge_test = Ridge(alpha=a)
    ridge_test.fit(X_train_poly_scaled, y_tr_poly)
    te_pred = ridge_test.predict(X_test_poly_scaled)
    tr_pred = ridge_test.predict(X_train_poly_scaled)
    name = f"Ridge_poly10_alpha_{a}"
    add_to_tables(name, y_tr_poly, tr_pred, y_te_poly, te_pred)

print("Подбор alpha для Ridge завершён")

ridge_rows = result_R2[result_R2['model'].str.contains('Ridge_poly10_alpha')]
display(ridge_rows.sort_values(by='test', ascending=False))

Подбор alpha для Ridge завершён

                       model     train      test
23     Ridge_poly10_alpha_10  0.464824  0.457947
22      Ridge_poly10_alpha_1  0.466699  0.449662
24    Ridge_poly10_alpha_100  0.459963  0.447575
25   Ridge_poly10_alpha_1000  0.453628  0.441468
21    Ridge_poly10_alpha_0.1  0.467774  0.433001
20  Ridge_poly10_alpha_0.001   0.46967  0.382685

# 9. Native models

## Calculate the mean and median metrics from the previous lesson and add the results to the final dataframe.

In [30]:
mean_val = y_train.mean()
median_val = y_train.median()

y_train_pred_mean = [mean_val] * len(y_train)
y_test_pred_mean = [mean_val] * len(y_test)
y_train_pred_median = [median_val] * len(y_train)
y_test_pred_median = [median_val] * len(y_test)

add_to_tables('Naive_Mean', y_train, y_train_pred_mean, y_test, y_test_pred_mean)
add_to_tables('Naive_Median', y_train, y_train_pred_median, y_test, y_test_pred_median)

print("Наивные модели (среднее и медиана) добавлены")

Наивные модели (среднее и медиана) добавлены

# 10. Compare results

## Print your final tables

In [31]:
print("========== ИТОГОВЫЕ ТАБЛИЦЫ ==========")
print("\nMAE (сортировка по тесту):")
display(result_MAE.sort_values(by='test'))

print("\nRMSE (сортировка по тесту):")
display(result_RMSE.sort_values(by='test'))

print("\nR² (сортировка по тесту, по убыванию):")
display(result_R2.sort_values(by='test', ascending=False))

========== ИТОГОВЫЕ ТАБЛИЦЫ ==========

MAE (сортировка по тесту):

                       model       train        test
1                 sklearn_lr  626.984466   638.01973
12           Linear_Standard  626.984466   638.01973
8              Linear_MinMax  626.984466   638.01973
5                   sk_ridge  626.984495  638.019789
13            Ridge_Standard  626.984758  638.020321
6                   sk_lasso  626.985752  638.034052
14            Lasso_Standard  627.023795  638.173474
9               Ridge_MinMax  627.287112  638.246716
10              Lasso_MinMax  628.291324  639.428595
7                 sk_elastic  628.224366   639.68324
0                  my_sgd_lr  633.008591  644.797241
3                   my_lasso  633.013291  644.803621
4                 my_elastic  635.419009  647.353136
2                   my_ridge  638.799933  650.837118
15       ElasticNet_Standard  662.528996  675.369835
17              Ridge_poly10  687.931986  699.305664
23     Ridge_poly10_alpha_10  687.931986  699.305664
22      Ridge_poly10_alpha_1  686.859149   699.53885
21    Ridge_poly10_alpha_0.1   686.45952  700.068772
20  Ridge_poly10_alpha_0.001  685.715888  701.308392
24    Ridge_poly10_alpha_100    691.0148  703.472637
25   Ridge_poly10_alpha_1000  696.206418   709.43804
18              Lasso_poly10  698.585245  712.051356
19            Elastic_poly10   711.81973  724.579994
16                 LR_poly10  685.518993  766.647085
11         ElasticNet_MinMax  901.185925  915.472799
27              Naive_Median  944.409371  963.000945
26                Naive_Mean  969.015413  983.848895

RMSE (сортировка по тесту):

                       model        train         test
9               Ridge_MinMax   840.225533   854.041749
1                 sklearn_lr   840.191884   854.114842
12           Linear_Standard   840.191884   854.114842
8              Linear_MinMax   840.191884   854.114842
5                   sk_ridge   840.191884   854.114857
13            Ridge_Standard   840.191885   854.114992
6                   sk_lasso   840.192234   854.127145
14            Lasso_Standard   840.223377   854.258959
10              Lasso_MinMax   840.750782    854.55044
7                 sk_elastic   840.949391   855.087456
0                  my_sgd_lr   844.075622   858.878885
3                   my_lasso   844.078919   858.884717
4                 my_elastic   845.400389   860.262492
2                   my_ridge   847.863238   862.737391
15       ElasticNet_Standard   874.213291   888.663844
17              Ridge_poly10   911.192315   925.875427
23     Ridge_poly10_alpha_10   911.192315   925.875427
22      Ridge_poly10_alpha_1    909.59421   932.924666
24    Ridge_poly10_alpha_100   915.320975   934.691606
25   Ridge_poly10_alpha_1000   920.673536   939.844255
18              Lasso_poly10   923.854861    942.65723
21    Ridge_poly10_alpha_0.1   908.676725   946.941082
19            Elastic_poly10   939.064094   954.108964
20  Ridge_poly10_alpha_0.001   907.056809   988.064446
11         ElasticNet_MinMax  1159.240348  1172.105542
26                Naive_Mean  1245.551112   1257.61048
27              Naive_Median  1271.515543  1285.372391
16                 LR_poly10    906.66754  5750.002855

R² (сортировка по тесту, по убыванию):

                       model     train       test
9               Ridge_MinMax   0.54494   0.538794
1                 sklearn_lr  0.544976   0.538715
12           Linear_Standard  0.544976   0.538715
8              Linear_MinMax  0.544976   0.538715
5                   sk_ridge  0.544976   0.538715
13            Ridge_Standard  0.544976   0.538715
6                   sk_lasso  0.544976   0.538702
14            Lasso_Standard  0.544942    0.53856
10              Lasso_MinMax  0.544371   0.538245
7                 sk_elastic  0.544156   0.537664
0                  my_sgd_lr   0.54076   0.533555
3                   my_lasso  0.540757   0.533549
4                 my_elastic  0.539317   0.532051
2                   my_ridge  0.536629   0.529355
15       ElasticNet_Standard   0.50738   0.500642
17              Ridge_poly10  0.464824   0.457947
23     Ridge_poly10_alpha_10  0.464824   0.457947
22      Ridge_poly10_alpha_1  0.466699   0.449662
24    Ridge_poly10_alpha_100  0.459963   0.447575
25   Ridge_poly10_alpha_1000  0.453628   0.441468
18              Lasso_poly10  0.449846   0.438119
21    Ridge_poly10_alpha_0.1  0.467774   0.433001
19            Elastic_poly10  0.431583   0.424384
20  Ridge_poly10_alpha_0.001   0.46967   0.382685
11         ElasticNet_MinMax  0.133789     0.1313
26                Naive_Mean       0.0  -0.000067
27              Naive_Median -0.042126  -0.044707
16                 LR_poly10  0.470125 -19.906085

## What is the best model?

In [32]:
best_r2 = result_R2.sort_values(by='test', ascending=False).iloc[0]
print(f"Лучшая модель по R² на тесте: {best_r2['model']} (R² = {best_r2['test']:.4f})")

best_mae = result_MAE.sort_values(by='test').iloc[0]
print(f"Лучшая модель по MAE на тесте: {best_mae['model']} (MAE = {best_mae['test']:.2f})")

Лучшая модель по R² на тесте: Ridge_MinMax (R² = 0.5388)
Лучшая модель по MAE на тесте: sklearn_lr (MAE = 638.02)

## Which is the most stable model?

In [33]:
result_R2['diff'] = abs(result_R2['train'] - result_R2['test'])
most_stable = result_R2.sort_values(by='diff').iloc[0]
print(f"Наиболее стабильная модель по R²: {most_stable['model']} (разница train-test = {most_stable['diff']:.4f})")

result_MAE['diff'] = abs(result_MAE['train'] - result_MAE['test'])
stable_mae = result_MAE.sort_values(by='diff').iloc[0]
print(f"Наиболее стабильная модель по MAE: {stable_mae['model']} (разница train-test = {stable_mae['diff']:.2f})")

Наиболее стабильная модель по R²: Naive_Mean (разница train-test = 0.0001)
Наиболее стабильная модель по MAE: Ridge_MinMax (разница train-test = 10.96)