## load_and_save

In [1]:
import pandas as pd

## read_csv

In [2]:
df = pd.read_csv(filepath_or_buffer="../data/feed-views.log",
                 sep='\t',
                 header=None,
                 skiprows=[2,3],
                 skipfooter=2,
                 names=['datetime', 'user'],
                 index_col='datetime',
                 engine='python')

## Rename datetime to date_time

In [3]:
df.index.name = 'date_time'

## to_csv

In [4]:
df.to_csv(sep=";", path_or_buf = "../data/feed-views-semicolon.log")

In [5]:
df.head()

                              user
date_time
2020-04-17 12:01:08.463179   artem
2020-04-17 12:01:23.743946   artem
2020-04-17 12:35:52.735016   artem
2020-04-17 12:36:21.401412  oksana
2020-04-17 12:36:22.023355  oksana

In [6]:
df.tail()

                                 user
date_time
2020-05-21 16:36:40.915488  ekaterina
2020-05-21 17:49:36.429237      maxim
2020-05-21 18:45:20.441142  valentina
2020-05-21 23:03:06.457819      maxim
2020-05-21 23:23:49.995349      pavel

## review

In [10]:
df.count()

user    1072
dtype: int64

In [8]:
df2 = pd.read_csv("../data/feed-views-semicolon.log", sep=';')
df2.head()

                    date_time    user
0  2020-04-17 12:01:08.463179   artem
1  2020-04-17 12:01:23.743946   artem
2  2020-04-17 12:35:52.735016   artem
3  2020-04-17 12:36:21.401412  oksana
4  2020-04-17 12:36:22.023355  oksana